### ISSUE TITLE
Basic beam search can be performed on a fairseq model translating from German to English on the IWSLT dataset as follows:

### ISSUE THREAD

**Issue by taineleau** [rycolab/uid-decoding#4]
But the code is for fr-en, are you using the same series of models from fairseq for de-en?

**Comment by cimeister** [comment]
Apologies, that was a typo! It is fixed now

**Comment by taineleau** [comment]
Hi @cimeister, thanks for fixing it. If I'd like to reproduce the result on "de-en", do I only need to change fr-en to de-en accordingly?
